# Generated by Django 5.0.7 on 2024-07-24 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_area', '0001_initial'),
        ('matters', '0001_initial'),
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('publishing_company', models.CharField(default='', max_length=30)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('knowledge_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='knowledge_area.knowledge_area')),
                ('matter', models.ManyToManyField(related_name='books', to='matters.matter')),
                ('writer', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='writers.writer')),
            ],
        ),
    ]
