# Generated by Django 5.0.7 on 2024-07-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=40)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRA', 'Brasil'), ('FRA', 'França'), ('COL', 'Colombia'), ('CHN', 'China'), ('JPN', 'Japão'), ('NLD', 'Holanda'), ('GRC', 'Grecia')], max_length=20, null=True)),
            ],
        ),
    ]
