# Generated by Django 5.0.7 on 2024-07-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRA', 'Brasil'), ('FRA', 'França'), ('COL', 'Colombia'), ('CHN', 'China'), ('JPN', 'Japão'), ('NLD', 'Holanda'), ('GRC', 'Grecia')], max_length=20, null=True),
        ),
    ]
